name: Cypress Tests with Report and Notification on TEAMS

on:
  schedule:
    - cron: "0 */6 * * *" # 6hours
  workflow_dispatch:

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install Cypress and reporter
        run: npm install cypress cypress-mochawesome-reporter

      - name: Run Cypress tests and capture results
        id: cypress
        continue-on-error: true
        env:
          CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_MOCHAWESOME_REPORT_DIR: cypress/reports
        run: |
          # Run Cypress and capture output
          npx cypress run --env email=$CYPRESS_EMAIL,password=$CYPRESS_PASSWORD \
            --reporter spec \
            | tee cypress_output.txt

          # Parse the summary line at the end of the output
          SUMMARY_LINE=$(grep -A1 "└─*" cypress_output.txt | tail -n 1)
          echo "Summary line: $SUMMARY_LINE"
          
          # Extract numbers using awk
          # The line format is like: "✖ 8 of 8 failed (100%) 01:16 24 3 9 - 12"
          # where the last numbers are: total passed failed pending skipped
          TOTAL=$(echo "$SUMMARY_LINE" | awk '{print $(NF-4)}')
          PASSED=$(echo "$SUMMARY_LINE" | awk '{print $(NF-3)}')
          FAILED=$(echo "$SUMMARY_LINE" | awk '{print $(NF-2)}')
          PENDING=$(echo "$SUMMARY_LINE" | awk '{print $(NF-1)}')
          SKIPPED=$(echo "$SUMMARY_LINE" | awk '{print $NF}')
          
          # Calculate success rate
          if [ $TOTAL -eq 0 ]; then
            SUCCESS_RATE=0
          else
            SUCCESS_RATE=$(awk "BEGIN {printf \"%.2f\", ($PASSED/$TOTAL) * 100}")
          fi
          
          # Debug output
          echo "Parsed Results:"
          echo "Total: $TOTAL"
          echo "Passed: $PASSED"
          echo "Failed: $FAILED"
          echo "Pending: $PENDING"
          echo "Skipped: $SKIPPED"
          echo "Success Rate: $SUCCESS_RATE%"
          
          # Set outputs
          echo "total=$TOTAL" >> $GITHUB_OUTPUT
          echo "passed=$PASSED" >> $GITHUB_OUTPUT
          echo "failed=$FAILED" >> $GITHUB_OUTPUT
          echo "skipped=$SKIPPED" >> $GITHUB_OUTPUT
          echo "success_rate=$SUCCESS_RATE" >> $GITHUB_OUTPUT

      - name: Debug - Check Reports Directory
        run: ls -R cypress/reports || echo "No reports generated"

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports/
          if-no-files-found: warn

      - name: Send notification to Microsoft Teams
        if: always()
        run: |
          # Determine status and color based on results
          if [ "${{ steps.cypress.outputs.failed }}" == "0" ]; then
            STATUS="✅ IR Daily Health Check tests completed successfully"
            COLOR="00FF00"  # Green
          else
            STATUS="❌ IR Daily Health Check tests failed"
            COLOR="FF0000"  # Red
          fi

          JSON_PAYLOAD=$(cat << EOF
          {
            "type": "message",
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "type": "AdaptiveCard",
                  "body": [
                    {
                      "type": "TextBlock",
                      "text": "$STATUS",
                      "weight": "bolder",
                      "size": "large",
                      "color": "${{ steps.cypress.outputs.failed == 0 && 'good' || 'attention' }}"
                    },
                    {
                      "type": "FactSet",
                      "facts": [
                        {
                          "title": "Total Tests",
                          "value": "${{ steps.cypress.outputs.total }}"
                        },
                        {
                          "title": "✅ Passed",
                          "value": "${{ steps.cypress.outputs.passed }}"
                        },
                        {
                          "title": "❌ Failed",
                          "value": "${{ steps.cypress.outputs.failed }}"
                        },
                        {
                          "title": "⏭️ Skipped",
                          "value": "${{ steps.cypress.outputs.skipped }}"
                        },
                        {
                          "title": "📈 Success Rate",
                          "value": "${{ steps.cypress.outputs.success_rate }}%"
                        }
                      ]
                    },
                    {
                      "type": "TextBlock",
                      "text": "[View Detailed Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})",
                      "wrap": true
                    }
                  ],
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "version": "1.0"
                }
              }
            ]
          }
          EOF
          )

          curl -H "Content-Type: application/json" -d "$JSON_PAYLOAD" $TEAMS_WEBHOOK_URL
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
