name: Cypress Tests with Report and Notification on TEAMS

on:
  workflow_dispatch:

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Cypress and reporter
        run: npm install cypress cypress-mochawesome-reporter

      - name: Run Cypress tests with Mochawesome
        env:
          CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
        run: |
          npx cypress run --env email=$CYPRESS_EMAIL,password=$CYPRESS_PASSWORD --reporter mochawesome --reporter-options "reportDir=cypress/reports,overwrite=false,html=true,json=true" | tee cypress-output.log

      - name: Extract test count from Cypress output
        id: extract_test_count
        run: |
          # More robust patterns to match Cypress output
          TOTAL_PATTERN="[[:space:]]([0-9]+)[[:space:]]total"
          PASSED_PATTERN="[[:space:]]([0-9]+)[[:space:]]passing"
          FAILED_PATTERN="[[:space:]]([0-9]+)[[:space:]]failing"
          SKIPPED_PATTERN="[[:space:]]([0-9]+)[[:space:]]skipped"
          
          # Extract counts using case-insensitive grep
          TEST_COUNT=$(grep -iP "$TOTAL_PATTERN" cypress-output.log | grep -oP "$TOTAL_PATTERN" | grep -oP "[0-9]+" || echo "0")
          PASS_COUNT=$(grep -iP "$PASSED_PATTERN" cypress-output.log | grep -oP "$PASSED_PATTERN" | grep -oP "[0-9]+" || echo "0")
          FAIL_COUNT=$(grep -iP "$FAILED_PATTERN" cypress-output.log | grep -oP "$FAILED_PATTERN" | grep -oP "[0-9]+" || echo "0")
          PENDING_COUNT=$(grep -iP "$SKIPPED_PATTERN" cypress-output.log | grep -oP "$SKIPPED_PATTERN" | grep -oP "[0-9]+" || echo "0")
          
          # Debug output
          echo "Found counts in log file:"
          echo "Total: $TEST_COUNT"
          echo "Passed: $PASS_COUNT"
          echo "Failed: $FAIL_COUNT"
          echo "Pending: $PENDING_COUNT"
          
          # Set environment variables
          echo "TEST_COUNT=$TEST_COUNT" >> $GITHUB_ENV
          echo "PASS_COUNT=$PASS_COUNT" >> $GITHUB_ENV
          echo "FAIL_COUNT=$FAIL_COUNT" >> $GITHUB_ENV
          echo "PENDING_COUNT=$PENDING_COUNT" >> $GITHUB_ENV

      - name: Debug - Display Cypress Output
        run: cat cypress-output.log

      # Rest of the steps remain the same...
      - name: Generate merged report
        if: always()
        run: |
          if ls cypress/reports/*.json 1>/dev/null 2>&1; then
            npx mochawesome-merge cypress/reports/*.json > cypress/reports/full_report.json
            npx marge cypress/reports/full_report.json -f report -o cypress/reports
          else
            echo "No JSON reports found. Skipping merge."
          fi

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: |
            cypress/reports
            cypress/screenshots
            cypress/videos
          retention-days: 30
          if-no-files-found: warn

      - name: Process and send results to Teams
        if: always()
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          # Calculate success rate
          if [ "$TEST_COUNT" -eq 0 ]; then
            SUCCESS_RATE="0.00"
          else
            SUCCESS_RATE=$(echo "scale=2; ($PASS_COUNT * 100)/$TEST_COUNT" | bc)
          fi

          # Determine status color
          if [ "$FAIL_COUNT" -eq 0 ]; then
            COLOR="good"
            STATUS="✅ Success"
          else
            COLOR="attention"
            STATUS="❌ Failed"
          fi

          # Create Teams message card
          curl -H "Content-Type: application/json" -X POST -d '{
            "type": "message",
            "attachments": [{
              "contentType": "application/vnd.microsoft.card.adaptive",
              "content": {
                "type": "AdaptiveCard",
                "body": [{
                  "type": "TextBlock",
                  "size": "Large",
                  "weight": "Bolder",
                  "text": "Cypress Test Results",
                  "color": "'"$COLOR"'"
                },
                {
                  "type": "TextBlock",
                  "text": "'"$STATUS"'",
                  "weight": "Bolder",
                  "color": "'"$COLOR"'"
                },
                {
                  "type": "FactSet",
                  "facts": [
                    { "title": "Total Tests", "value": "'"$TEST_COUNT"'" },
                    { "title": "Passed", "value": "'"$PASS_COUNT"'" },
                    { "title": "Failed", "value": "'"$FAIL_COUNT"'" },
                    { "title": "Pending", "value": "'"$PENDING_COUNT"'" },
                    { "title": "Success Rate", "value": "'"$SUCCESS_RATE"'%" }
                  ]
                }],
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "version": "1.2"
              }
            }]
          }' $TEAMS_WEBHOOK_URL
